# https://stackoverflow.com/questions/31029095/disable-registry-update-in-cargo
# https://doc.rust-lang.org/cargo/reference/config.html

# /root/.cargo/config

[source.crates-io]
replace-with = 'local'
 
[source.local]
registry = "file:///root/crates.io-index"
