name: KCLVM-actions
on: [push]
jobs:
  test-unit:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
         submodules: 'true'
      - name: Build KCLVM
        run: make build
        shell: bash
      - name: Grammar test
        run: |
          chmod +x ./internal/kclvm_py/scripts/test_grammar.sh
          topdir=$(realpath $(dirname $0)) ./internal/kclvm_py/scripts/test_grammar.sh
        shell: bash
      - name: Internal python unit test
        run: |
          chmod +x ./internal/kclvm_py/scripts/test_unit.sh
          ./internal/kclvm_py/scripts/test_unit.sh
        shell: bash
      - name: Delete rust cargo
        run: rm -rf /root/.cargo/bin
        shell: bash
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy, rustfmt
      - name: Rust unit test
        working-directory: ./kclvm
        run: make test
        shell: bash
