name: KCLVM-actions
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-unit:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build KCLVM
        run: make build && make
