name: KCLVM-actions
on: [push]
jobs:
  test-unit:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build KCLVM
        run: make build
      - name: Grammar test
        run: |
          export PATH=$PATH:./_build/dist/ubuntu/kclvm/bin
          chmod +x ./scripts/test_grammar.sh
          topdir=$(realpath $(dirname $0)) ./scripts/test_grammar.sh
