name: KCLVM-actions
on: [push]
jobs:
  test-unit:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: kusionstack/kclvm-builder
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build KCLVM
        run: make build
        shell: bash
      - name: Grammar test
        run: |
          TOP_DIR = $(realpath $(dirname $0)/../)
          echo PATH=$PATH:$TOP_DIR/_build/dist/ubuntu/kclvm/bin >> ~/.bash_profile
          source ~/.bash_profile
          chmod +x ./scripts/test_grammar.sh
          topdir=$(realpath $(dirname $0)) ./scripts/test_grammar.sh
        shell: bash
      - name: Internal python unit test
        run: |
          TOP_DIR = $(realpath $(dirname $0)/../)
          echo PATH=$PATH:$TOP_DIR/_build/dist/ubuntu/kclvm/bin >> ~/.bash_profile
          source ~/.bash_profile
          chmod +x ./scripts/unittest_coverage.sh
          ./scripts/unittest_coverage.sh
        shell: bash
      - name: Rust unit test
        run: |
          TOP_DIR = $(realpath $(dirname $0)/../)
          echo PATH=$PATH:$TOP_DIR/_build/dist/ubuntu/kclvm/bin >> ~/.bash_profile
          source ~/.bash_profile
          cd ./kclvm/tests/test_units
          python3 -m pip install pytest
          PYTHONPATH=./kclvm/plugin python3 -m pytest -vv || { echo 'kclvmx/tests/test_units failed' ; exit 1; }
          cd ./kclvm/ast
          cargo test || { echo 'kclvmx/ast test failed' ; exit 1; }
          cd ./kclvm/lexer
          cargo test || { echo 'kclvmx/lexer test failed' ; exit 1; }
          cd ./kclvm/parser
          cargo test || { echo 'kclvmx/parser test failed' ; exit 1; }
          cd ./kclvm/compiler
          cargo test || { echo 'kclvmx/compiler test failed' ; exit 1; }
          cd ./kclvm/config
          cargo test || { echo 'kclvmx/config test failed' ; exit 1; }
        shell: bash
