name: KCLVM GitHub Actions
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: install Rust
        run: |
          apt-get update
          apt-get install -y git wget curl
          apt-get install -y make gcc patch g++ swig
          apt-get install -y python-dev libffi-dev
          apt-get install -y zlib1g-dev ncurses-dev
          curl https://sh.rustup.rs -sSf | bash -s -- -y
          cargo version
