name: actions
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
  test-unit:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run units tests.
        run: make test
  test-grammar:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run grammar tests.
        run: make test-grammar
